/** Generate an Ansible inventory from stable Heat output names. */

import { writeFileSync } from 'node:fs';
import { stringify } from 'yaml';
import { banner, success, error } from '../../infrastructure/cli.js';
import { INVENTORY_PATH, SSH_KEY_PATH } from '../../infrastructure/paths.js';
import { openstackStackRepository } from '../../infrastructure/repositories/openstack-stack-repository.js';
import { listStacks } from '../../domain/usecases/list-stacks.js';
import { getStackOutputs } from '../../domain/usecases/get-stack-outputs.js';

function parseIpList(value: string | undefined): string[] {
  if (!value) return [];
  if (value.startsWith('[')) {
    try {
      const parsed: unknown = JSON.parse(value.replace(/'/g, '"'));
      if (Array.isArray(parsed)) return parsed.map(String);
    } catch {
      // OpenStack clients may render lists as comma-separated strings.
    }
  }
  return value.split(',').map((ip) => ip.trim()).filter(Boolean);
}

function legacyNodeIps(outputs: Record<string, string>): string[] {
  return Object.entries(outputs)
    .filter(([key]) => /^node\d+_private_ip$/.test(key))
    .sort(([left], [right]) => left.localeCompare(right, undefined, { numeric: true }))
    .map(([, value]) => value);
}

function managerIps(outputs: Record<string, string>): string[] {
  return parseIpList(outputs.manager_private_ips)
    .concat(parseIpList(outputs.swarm_private_ips))
    .concat(legacyNodeIps(outputs))
    .concat(outputs.private_ip ? [outputs.private_ip] : [])
    .filter((ip, index, all) => all.indexOf(ip) === index);
}

function buildInventory(stackName: string, outputs: Record<string, string>): object {
  const managers = managerIps(outputs);
  if (managers.length === 0) throw new Error('No manager IPs found in stack outputs.');

  const bastionIp = outputs.bastion_floating_ip;
  const gatewayIp = outputs.gateway_floating_ip;
  const sshIp = outputs.ssh_floating_ip;
  const jumpIp = bastionIp || gatewayIp || sshIp;
  const directFloatingIps = [outputs.floating_ip, outputs.node1_floating_ip, outputs.node2_floating_ip, outputs.node3_floating_ip]
    .filter((value): value is string => Boolean(value));

  const managerHosts = Object.fromEntries(managers.map((ip, index) => {
    const isSshEntryManager = Boolean(sshIp) && index === 0;
    return [
      `${stackName}-manager-${index + 1}`,
      {
        ansible_host: isSshEntryManager ? sshIp : (jumpIp ? ip : (directFloatingIps[index] ?? ip)),
        private_ip: ip,
        ...(!isSshEntryManager && jumpIp ? {
          // OpenSSH does not apply the target's IdentityFile to ProxyJump.
          // An explicit ProxyCommand keeps the generated project key scoped to
          // both hops and does not depend on an operator's ssh-agent contents.
          ansible_ssh_common_args: `-o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -o ProxyCommand="ssh -i ${SSH_KEY_PATH} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -W %h:%p ubuntu@${jumpIp}"`,
        } : {}),
      },
    ];
  }));

  const children: Record<string, unknown> = {
    managers: { hosts: managerHosts },
    workers: { hosts: {} },
  };

  if (bastionIp) {
    children.bastion = { hosts: { [`${stackName}-bastion`]: { ansible_host: bastionIp } } };
  } else if (gatewayIp) {
    children.bastion = { hosts: { [`${stackName}-gateway`]: { ansible_host: gatewayIp } } };
  }

  return {
    all: {
      vars: {
        ansible_user: 'ubuntu',
        ansible_python_interpreter: '/usr/bin/python3',
        ansible_ssh_private_key_file: SSH_KEY_PATH,
        ansible_ssh_common_args: '-o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new',
      },
      children,
    },
  };
}

export async function run(args: string[]): Promise<void> {
  banner('TOAD Ansible Inventory Generator');
  const stackName = args[0];

  if (!stackName) {
    console.log('Usage: pnpm run inventory <stack-name>\n');
    console.log('Available stacks:');
    try {
      const stacks = listStacks(openstackStackRepository);
      console.log(stacks.length ? stacks.map((stack) => `  ${stack.name}`).join('\n') : '(no stacks found)');
    } catch {
      console.log('(failed to list stacks)');
    }
    process.exitCode = 1;
    return;
  }

  try {
    const outputs = getStackOutputs(openstackStackRepository, stackName);
    const inventory = `# Generated by TOAD for ${stackName}\n${stringify(buildInventory(stackName, outputs))}`;
    const inventoryPath = INVENTORY_PATH;
    writeFileSync(inventoryPath, inventory, { mode: 0o600 });
    success(`Inventory written to: ${inventoryPath}`);
  } catch (cause) {
    error(cause instanceof Error ? cause.message : 'Failed to generate inventory.');
    process.exitCode = 1;
  }
}
