#!/usr/bin/env npx tsx
/**
 * Generate Ansible inventory from a deployed stack.
 *
 * Reads stack outputs and creates an inventory.yaml file with:
 * - Host groups (bastion, gateways, swarm managers/workers)
 * - SSH connection settings (key, user, jump host)
 * - ProxyCommand for nodes behind bastion/gateway
 *
 * The generated inventory is ready for use with Ansible playbooks.
 *
 * Usage:
 *   pnpm run inventory my-stack
 *
 * Output: inventory.yaml in project root
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { banner, section, success, error } from '../../infrastructure/cli.js';
import { ROOT_DIR, SSH_KEY_PATH } from '../../infrastructure/paths.js';
import { openstackStackRepository } from '../../infrastructure/repositories/openstack-stack-repository.js';
import { listStacks } from '../../domain/usecases/list-stacks.js';
import { getStackOutputs } from '../../domain/usecases/get-stack-outputs.js';

function parseIpList(value: string): string[] {
  if (!value) return [];
  if (value.startsWith('[')) {
    try { return JSON.parse(value.replace(/'/g, '"')); } catch { /* fall through */ }
  }
  return value.split(',').map(ip => ip.trim()).filter(Boolean);
}

function generateLevel5Inventory(stackName: string, outputs: Record<string, string>): string {
  const jumpIp = outputs.bastion_floating_ip;

  let inventory = `# Ansible inventory for ${stackName} (Level 5 - HA)
# Generated by: pnpm run inventory ${stackName}

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ${SSH_KEY_PATH}
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    bastion:
      hosts:
        toad-bastion:
          ansible_host: ${outputs.bastion_floating_ip}

    gateways:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i ${SSH_KEY_PATH} ubuntu@${jumpIp}"'
      hosts:
`;

  const gatewayIps = parseIpList(outputs.gateway_private_ips);
  gatewayIps.forEach((ip: string, i: number) => {
    inventory += `        toad-gateway-${i + 1}:\n          ansible_host: ${ip}\n`;
  });

  inventory += `
    swarm:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i ${SSH_KEY_PATH} ubuntu@${jumpIp}"'
      children:
        managers:
          hosts:
`;

  const swarmIps = parseIpList(outputs.swarm_private_ips);
  if (swarmIps.length > 0) {
    inventory += `            toad-swarm-1:\n              ansible_host: ${swarmIps[0]}\n`;
    inventory += `\n        workers:\n          hosts:\n`;
    swarmIps.slice(1).forEach((ip: string, i: number) => {
      inventory += `            toad-swarm-${i + 2}:\n              ansible_host: ${ip}\n`;
    });
  }

  return inventory;
}

function generateLevel4Inventory(stackName: string, outputs: Record<string, string>): string {
  const jumpIp = outputs.gateway_floating_ip;

  let inventory = `# Ansible inventory for ${stackName} (Level 4 - Standard)
# Generated by: pnpm run inventory ${stackName}

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ${SSH_KEY_PATH}
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    gateway:
      hosts:
        toad-gateway:
          ansible_host: ${outputs.gateway_floating_ip}

    swarm:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i ${SSH_KEY_PATH} ubuntu@${jumpIp}"'
      children:
        managers:
          hosts:
`;

  const swarmIps = parseIpList(outputs.swarm_private_ips);
  if (swarmIps.length > 0) {
    inventory += `            toad-swarm-1:\n              ansible_host: ${swarmIps[0]}\n`;
    inventory += `\n        workers:\n          hosts:\n`;
    swarmIps.slice(1).forEach((ip: string, i: number) => {
      inventory += `            toad-swarm-${i + 2}:\n              ansible_host: ${ip}\n`;
    });
  }

  return inventory;
}

function generateSimpleInventory(stackName: string, outputs: Record<string, string>): string {
  return `# Ansible inventory for ${stackName}
# Generated by: pnpm run inventory ${stackName}

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ${SSH_KEY_PATH}
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  hosts:
    toad-node:
      ansible_host: ${outputs.floating_ip}
`;
}

export async function run(args: string[]): Promise<void> {
  banner('TOAD Ansible Inventory Generator');

  const stackName = args[0];

  if (!stackName) {
    console.log('Usage: pnpm run inventory <stack-name>\n');
    console.log('Available stacks:');

    try {
      const stacks = listStacks(openstackStackRepository);
      if (stacks.length > 0) {
        stacks.forEach(s => console.log(`  ${s.name}`));
      } else {
        console.log('(no stacks found)');
      }
    } catch {
      console.log('(failed to list stacks)');
    }
    process.exit(1);
  }

  console.log(`Generating inventory for stack: ${stackName}\n`);

  // Get stack outputs
  let outputs: Record<string, string>;
  try {
    outputs = getStackOutputs(openstackStackRepository, stackName);
  } catch {
    error('Failed to get stack outputs. Is the stack deployed?');
    process.exit(1);
  }

  // Generate inventory based on stack type
  let inventory: string;

  if (outputs.bastion_floating_ip) {
    inventory = generateLevel5Inventory(stackName, outputs);
  } else if (outputs.gateway_floating_ip) {
    inventory = generateLevel4Inventory(stackName, outputs);
  } else if (outputs.floating_ip) {
    inventory = generateSimpleInventory(stackName, outputs);
  } else {
    error('Could not determine stack type from outputs');
    process.exit(1);
  }

  // Write inventory file
  const inventoryPath = join(ROOT_DIR, 'inventory.yaml');
  writeFileSync(inventoryPath, inventory);

  success('Inventory written to: inventory.yaml\n');
  console.log('Preview:');
  section('', 50);
  console.log(inventory);
  section('', 50);
  console.log('\nUsage:');
  console.log('  ansible-playbook -i inventory.yaml your-playbook.yaml');
  console.log('  ansible all -i inventory.yaml -m ping\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  run(process.argv.slice(2));
}
