services:
  web:
    image: nginx:1.31.0-alpine@sha256:2f07d83bf561b506400dc183b1b2003803e39efbd22451f848adaba14d28c7c7
    security_opt: [no-new-privileges:true]
    volumes:
      - site-data:/usr/share/nginx/html
    networks: [traefik-public]
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 16M
      placement:
        constraints:
          - node.labels.toad.stateful-primary == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.stateful-example.rule=Host(`stateful-example.${TOAD_DOMAIN}`)"
        - "traefik.http.routers.stateful-example.entrypoints=websecure"
        - "traefik.http.routers.stateful-example.tls=true"
        - "traefik.http.routers.stateful-example.tls.certresolver=letsencrypt"
        - "traefik.http.services.stateful-example.loadbalancer.server.port=80"
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback

volumes:
  site-data:

networks:
  traefik-public:
    external: true
