swarm:
  hosts:
    main:
      ansible_host: test-ts
      private_ip: IP.ADDRESS
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/certificates/swarm-admin.key
  children:
    workers:
      hosts:
        worker-0:
          ansible_host: IP.ADDRESS.01
        worker-1:
          ansible_host: IP.ADDRESS.02
        worker-2:
          ansible_host: IP.ADDRESS.03
      vars:
        ansible_user: debian
        ansible_ssh_private_key_file: ~/.ssh/certificates/bastion-key.key
        ansible_ssh_common_args: '-o ProxyJump=debian@test-ts -o StrictHostKeyChecking=accept-new'
